services:
  hlasys2:
    build: .
    image: hlasys2
    ports:
      - 5000:5000
    volumes:
      # for sqlite database inside
      - ./container-data/instance:/hlasys2/instance
      - ./container-data/config.py:/hlasys2/hlasys2_app/config.py:ro
      - ./container-data/client_secrets.json:/hlasys2/client_secrets.json:ro
