[tool.poetry]
name = "hlasys2"
version = "0.0.1"
description = "Web based voting system for hkfree.org"
authors = ["Your Name <you@example.com>"]
license = "GNU GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.3"
Flask-WTF = "^1.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
