[tool.poetry]
name = "hlasys2"
version = "2.0.4"
description = "Web based voting system for hkfree.org"
authors = ["Ondřej Pithart <ondra@pithart.com>"]
license = "GNU GPLv3"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^3.0.3"
Flask-WTF = "^1.2.1"
flask-oidc = "^2.3.1"
oidc-register = "^0.2.1"
waitress = "^3.0.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
