on:
  push:
    branches:
      - rework1 # Later to be renamed to something like development

jobs:
  build:
    runs-on: buildah

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          buildah build \
          --build-arg HLASYS2_REF_NAME=${{ forgejo.ref_name }} \
          --build-arg HLASYS2_COMMIT_HASH=${{ forgejo.sha }} \
          -t hlasys2 .

      - name: Push built image
        # This really is not a good way to do this.
        run: buildah push --creds mrreactive:${{ secrets.HLASYS_DEV_SECRET }} hlasys2 code.darkne.dev/nextgenerationnetwork/hlasys2:development
